FROM python:3.14-slim

ENV PIP_ROOT_USER_ACTION=ignore
RUN pip install --upgrade pip
COPY . /app
RUN pip install -e /app
WORKDIR /app/example
RUN python manage.py migrate

EXPOSE 8000/tcp
ENTRYPOINT ["python", "manage.py", "runserver", "0.0.0.0:8000"]
