# Generated by Django 5.1.1 on 2024-09-25 23:13

from django.db import migrations


def create_demo_objects(apps, schema_editor):
    Item = apps.get_model('example', 'Item')
    items = []
    for string in ('test one', 'test two', 'test three'):
        items.append(Item.objects.create(name=string))
    Collection = apps.get_model('example', 'Collection')
    collection = Collection.objects.create(name='Test Collection', primary=items[0])
    collection.items.set(items)


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_demo_objects)
    ]
